services:
  localstack:
    image: localstack/localstack:latest
    environment:
      - SERVICES=apigateway,lambda,sns,sqs,dynamodb,s3,iam,cloudwatch,logs,sts
      - LAMBDA_EXECUTOR=docker-reuse
      - AWS_DEFAULT_REGION=us-east-1
      - DEBUG=1
    ports:
      - "4566:4566"
      - "4510-4559:4510-4559"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
      - "./.localstack:/var/lib/localstack"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:4566/_localstack/health"]
      interval: 5s
      timeout: 3s
      retries: 30

  postgres:
    image: postgres:16
    environment:
      - POSTGRES_DB=payments
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports: ["5432:5432"]
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d payments"]
      interval: 5s
      timeout: 3s
      retries: 20

  terraform:
    image: hashicorp/terraform:1.7
    working_dir: /workspace/terraform
    volumes:
      - ./:/workspace
      - ./build:/workspace/build
    environment:
      - AWS_ACCESS_KEY_ID=test
      - AWS_SECRET_ACCESS_KEY=test
      - AWS_DEFAULT_REGION=us-east-1
    network_mode: host
    entrypoint: []
    command: ["sleep", "infinity"]
    depends_on:
      localstack:
        condition: service_healthy
